# Workflow name
name: 'Chromatic Deployment'

on:
  push:
    branches:
      - deploy
  # pull_request:
  #   branches: [deploy]

jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: install
        run: npm i
      - name: Publish to Chromatic
        uses: chromaui/action@latest
      - run: npm run chromatic
        # with:
        #   projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        #   token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          sed -i "s|CHROMATIC_HOMEPAGE|${{ steps.chromatic.outputs.storybookUrl }}|" package.json
      - run: yarn publish:npm-outDir
      - run: |
          sed -i "s|${{ steps.chromatic.outputs.storybookUrl }}|CHROMATIC_HOMEPAGE|" package.json
      - run: cp -R build/* dist/
      - run: |
          git config --global user.name "KimDanwoo"
          git config --global user.email "dudgh9198@naver.com"
      - run: |
          git add dist
          git commit -am 'build: automate deploy dist'
          git push -f https://${{ secrets.GIT_AUTH_TOKEN }}@github.com/KimDanwoo/d-story.git HEAD:dist-build
